# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 10 to 49

In [5]:
a=np.arange(10,50)

4. Find the shape of previous array in question 3

In [6]:
np.shape(a)

(40,)

5. Print the type of the previous array in question 3

In [8]:
a.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [11]:
# print(np.__version__)
np.version.version

'1.18.1'

7. Print the dimension of the array in question 3


In [12]:
np.ndim(a)

1

8. Create a boolean array with all the True values

In [53]:
np.ones((5,5),dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

9. Create a two dimensional array




In [40]:
# b=np.arange(10).reshape(2,5)
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [51]:
c=np.arange(20).reshape(2,5,2)
# np.ndim(c)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [73]:
a=np.array([1,2,3,4,5])
np.flip(a,0)

array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [68]:
c=np.zeros(11)
c[5] =1
c

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [61]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [84]:
x = np.array([1,2,3,4,5])

x.dtype

dtype('int32')

In [86]:
y=x.astype('float32')
y

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [3]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [6]:
compare=arr1 == arr2
compare

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [13]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [15]:
arr = -1
arr

-1

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [28]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [39]:
# np.array([(1,1,1),(0,0,0),(1,1,1)])
np.array([[1,1,1],
           [0,0,0],
           [1,1,1]
                  ])

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [43]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [54]:

arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  [[7, 8, 9], 
                   [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [69]:
c= np.arange(10).reshape(2,5)
c[0]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [70]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
c[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [74]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
# pending

26. Create a 10x10 array with random values and find the minimum and maximum values

In [91]:
f= np.random.rand(10,10)
f

array([[0.06232194, 0.81430318, 0.95800119, 0.18782238, 0.87289412,
        0.29255443, 0.57535973, 0.95436764, 0.53479047, 0.03628687],
       [0.1025479 , 0.81805703, 0.06635314, 0.35110661, 0.90039056,
        0.6712496 , 0.95369895, 0.64974167, 0.13327863, 0.79213575],
       [0.41757582, 0.32213912, 0.90054675, 0.53532278, 0.76388693,
        0.42077407, 0.06284066, 0.94272419, 0.63880367, 0.90428817],
       [0.76296076, 0.33465837, 0.07187833, 0.83712207, 0.06240689,
        0.52645424, 0.44720791, 0.76760831, 0.36659786, 0.49672763],
       [0.22384642, 0.76575724, 0.22273533, 0.8739785 , 0.74736121,
        0.10718128, 0.75724872, 0.16655837, 0.20107072, 0.95394884],
       [0.38570933, 0.30920332, 0.1676262 , 0.23409246, 0.14092774,
        0.88651114, 0.20262289, 0.05158634, 0.86190316, 0.07712023],
       [0.03342809, 0.35577561, 0.66664751, 0.67180503, 0.17472268,
        0.76744127, 0.69099106, 0.5270005 , 0.00137113, 0.68921824],
       [0.5940326 , 0.26149135, 0.6200375

In [92]:
np.min(f)

0.0013711324011905779

In [93]:
np.max(f)

0.95800118656528

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [99]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [102]:
# pending

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [109]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)


In [110]:
# pending

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
# pending

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [167]:
intg=np.arange(1,16).reshape(5,3)
intg

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [169]:
decimal = intg.astype('float32')
decimal

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [150]:
d=np.arange(1,17).reshape(2,2,4)
g = d.astype('float32')
g

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [156]:
d=np.arange(1,17).reshape(2,2,4)
np.swapaxes(d,axis1=1, axis2=0)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [133]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [170]:
# pending

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [127]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a= np.unique(names)
np.sort(a)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [177]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
index = [4]
a = np.delete(a, index)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [190]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
delet= np.delete(sampleArray,2,1)
delet

array([[34, 43],
       [82, 22],
       [53, 94]])

In [194]:
# np.append(delet,newColumn,axis=1)    
# trying but comes error

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [116]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [113]:
a = np.random.randn(20)
np.cumsum(a)

array([ 1.02900399,  1.14866119,  1.04282966,  1.5560143 ,  1.72393639,
        2.05046703,  2.14890817,  3.35238183,  3.97400107,  5.1547149 ,
        6.76655499,  7.20037273,  6.28931895,  7.34866941,  6.74257967,
        7.76752717,  8.27326004, 10.04172353, 10.5053157 , 10.36274137])